### ISSUE TITLE
Lab10: formatting issue of csharp code

### ISSUE THREAD

**Issue by houbena** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#351] opened 2021-12-16 13:05 UTC
# Module: 10
#### Step: 17

Description of issue
Code snippet is not formatted correctly. Please see screenshot below

![image](https://user-images.githubusercontent.com/8375842/146377180-f71aaa5f-3dfd-4053-a9dc-2c188a00865e.png)

**Comment by unaihuete93** [comment] 2021-12-17 10:33
![image](https://user-images.githubusercontent.com/64772417/146531164-93eafa4d-f5a3-4c58-a679-6d7a6afbfc3c.png)
![image](https://user-images.githubusercontent.com/64772417/146531205-45f7009f-63d9-4297-a6ea-31d2597fb8f3.png)

**Comment by MOC-Labs-Review** [comment] 2022-02-01 15:25
MOC-Labs-Review found Module 10 worked as written

**Comment by VitalyMCT** [comment] 2022-02-04 16:14
@JeffKoMS  Can this PR be approved please?

**Comment by unaihuete93** [comment] 2022-03-28 11:35
any update?

**Comment by MOC-Labs-Review** [comment] 2022-04-11 21:27
MOC Labs Review confirms this issue.

**Comment by JeffKoMS** [comment] 2022-04-14 18:19
@MOC-Labs-Review The markdown for this is formatted correctly, can you please investigate why it's not being rendered correctly?

![image](https://user-images.githubusercontent.com/25939240/163452594-7b3ea72c-ab44-492d-9198-1ad1209c0d05.png)

**Comment by JeffKoMS** [comment] 2022-04-26 21:13
Update: I've escalated to the Skillable support team directly.

**Comment by JeffKoMS** [comment] 2022-04-27 18:23
The answer to the problem is to remove blank lines in the code blocks. I've created a PR #466 that I'll merge on Friday to minimize any potential impact to students. Removing blank lines will make the code a bit more difficult to parse, but the other option was to make all code blocks break out of their indentations in the numbered lists.

I've also performed a general cleanup of the markdown. I'm going to close this issue, but will encourage anyone to open another one post the PR merge this Friday.

**Closed by JeffKoMS** 2022-04-27 18:23 UTC
