### ISSUE TITLE
Exercise 2: Configure a local Azure Functions project - Task 1: Initialize a function project

### ISSUE THREAD

**Issue by sudlo** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#354] opened 2021-12-18 16:37 UTC
Exercise 2: Configure a local Azure Functions project

Task 1: Initialize a function project
#### Step: 01

Description of issue:

I am trying to configure local azure function project, initialize a function project.

to create a new local Azure Functions project in the current directory using the dotnet runtime: using the command  `func init --worker-runtime dotnet --force` ran successfully.

Task 2: Configure a connection string 

changed the string to my storage account 

Repro steps:

Task 3: Build and validate a project: when trying to build and validate the project we get the errors 

I have uploaded the lab files on to my cloud shell so it would be easier to work upon [correct me if i am wrong here]

1.  changed the current directory - PS /home/sudeep/AZ-204-DevelopingSolutionsforMicrosoftAzure-master/Allfiles/Labs/02/Starter/func>
2. dotnet build
3. we get the following error message

`/home/sudeep/.nuget/packages/microsoft.net.sdk.functions/1.0.36/build/Microsoft.NET.Sdk.Functions.Build.targets(44,5): error : It was not possible to find any compatible framework version [/home/sudeep/AZ-204-DevelopingSolutionsforMicrosoftAzure-master/Allfiles/Labs/02/Starter/func/func.csproj]
/home/sudeep/.nuget/packages/microsoft.net.sdk.functions/1.0.36/build/Microsoft.NET.Sdk.Functions.Build.targets(44,5): error : The framework 'Microsoft.NETCore.App', version '2.1.0' was not found. [/home/sudeep/AZ-204-DevelopingSolutionsforMicrosoftAzure-master/Allfiles/Labs/02/Starter/func/func.csproj]
/home/sudeep/.nuget/packages/microsoft.net.sdk.functions/1.0.36/build/Microsoft.NET.Sdk.Functions.Build.targets(44,5): error :   - The following frameworks were found: [/home/sudeep/AZ-204-DevelopingSolutionsforMicrosoftAzure-master/Allfiles/Labs/02/Starter/func/func.csproj]
/home/sudeep/.nuget/packages/microsoft.net.sdk.functions/1.0.36/build/Microsoft.NET.Sdk.Functions.Build.targets(44,5): error :       3.1.9 at [/usr/share/dotnet/shared/Microsoft.NETCore.App] [/home/sudeep/AZ-204-DevelopingSolutionsforMicrosoftAzure-master/Allfiles/Labs/02/Starter/func/func.csproj]
/home/sudeep/.nuget/packages/microsoft.net.sdk.functions/1.0.36/build/Microsoft.NET.Sdk.Functions.Build.targets(44,5): error :  [/home/sudeep/AZ-204-DevelopingSolutionsforMicrosoftAzure-master/Allfiles/Labs/02/Starter/func/func.csproj]
/home/sudeep/.nuget/packages/microsoft.net.sdk.functions/1.0.36/build/Microsoft.NET.Sdk.Functions.Build.targets(44,5): error : You can resolve the problem by installing the specified framework and/or SDK. [/home/sudeep/AZ-204-DevelopingSolutionsforMicrosoftAzure-master/Allfiles/Labs/02/Starter/func/func.csproj]
/home/sudeep/.nuget/packages/microsoft.net.sdk.functions/1.0.36/build/Microsoft.NET.Sdk.Functions.Build.targets(44,5): error :  [/home/sudeep/AZ-204-DevelopingSolutionsforMicrosoftAzure-master/Allfiles/Labs/02/Starter/func/func.csproj]
/home/sudeep/.nuget/packages/microsoft.net.sdk.functions/1.0.36/build/Microsoft.NET.Sdk.Functions.Build.targets(44,5): error : The specified framework can be found at: [/home/sudeep/AZ-204-DevelopingSolutionsforMicrosoftAzure-master/Allfiles/Labs/02/Starter/func/func.csproj]
/home/sudeep/.nuget/packages/microsoft.net.sdk.functions/1.0.36/build/Microsoft.NET.Sdk.Functions.Build.targets(44,5): error :   - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=cbld.10-x64 [/home/sudeep/AZ-204-DevelopingSolutionsforMicrosoftAzure-master/Allfiles/Labs/02/Starter/func/func.csproj]
/home/sudeep/.nuget/packages/microsoft.net.sdk.functions/1.0.36/build/Microsoft.NET.Sdk.Functions.Build.targets(44,5): error :  [/home/sudeep/AZ-204-DevelopingSolutionsforMicrosoftAzure-master/Allfiles/Labs/02/Starter/func/func.csproj]
/home/sudeep/.nuget/packages/microsoft.net.sdk.functions/1.0.36/build/Microsoft.NET.Sdk.Functions.Build.targets(44,5): error : Metadata generation failed. [/home/sudeep/AZ-204-DevelopingSolutionsforMicrosoftAzure-master/Allfiles/Labs/02/Starter/func/func.csproj]

Build FAILED.

/home/sudeep/AZ-204-DevelopingSolutionsforMicrosoftAzure-master/Allfiles/Labs/02/Starter/func/func.csproj : warning NU1603: Microsoft.Azure.WebJobs.Extensions 3.0.5 depends on Microsoft.Azure.WebJobs.Host.Storage (>= 3.0.11) but Microsoft.Azure.WebJobs.Host.Storage 3.0.11 was not found. An approximate best match of Microsoft.Azure.WebJobs.Host.Storage 3.0.13 was resolved.
/home/sudeep/AZ-204-DevelopingSolutionsforMicrosoftAzure-master/Allfiles/Labs/02/Starter/func/func.csproj : warning NU1603: Microsoft.Azure.WebJobs.Extensions 3.0.5 depends on Microsoft.Azure.WebJobs.Host.Storage (>= 3.0.11) but Microsoft.Azure.WebJobs.Host.Storage 3.0.11 was not found. An approximate best match of Microsoft.Azure.WebJobs.Host.Storage 3.0.13 was resolved.
/home/sudeep/.nuget/packages/microsoft.net.sdk.functions/1.0.36/build/Microsoft.NET.Sdk.Functions.Build.targets(44,5): error : It was not possible to find any compatible framework version [/home/sudeep/AZ-204-DevelopingSolutionsforMicrosoftAzure-master/Allfiles/Labs/02/Starter/func/func.csproj]
/home/sudeep/.nuget/packages/microsoft.net.sdk.functions/1.0.36/build/Microsoft.NET.Sdk.Functions.Build.targets(44,5): error : The framework 'Microsoft.NETCore.App', version '2.1.0' was not found. [/home/sudeep/AZ-204-DevelopingSolutionsforMicrosoftAzure-master/Allfiles/Labs/02/Starter/func/func.csproj]
/home/sudeep/.nuget/packages/microsoft.net.sdk.functions/1.0.36/build/Microsoft.NET.Sdk.Functions.Build.targets(44,5): error :   - The following frameworks were found: [/home/sudeep/AZ-204-DevelopingSolutionsforMicrosoftAzure-master/Allfiles/Labs/02/Starter/func/func.csproj]
/home/sudeep/.nuget/packages/microsoft.net.sdk.functions/1.0.36/build/Microsoft.NET.Sdk.Functions.Build.targets(44,5): error :       3.1.9 at [/usr/share/dotnet/shared/Microsoft.NETCore.App] [/home/sudeep/AZ-204-DevelopingSolutionsforMicrosoftAzure-master/Allfiles/Labs/02/Starter/func/func.csproj]
/home/sudeep/.nuget/packages/microsoft.net.sdk.functions/1.0.36/build/Microsoft.NET.Sdk.Functions.Build.targets(44,5): error :  [/home/sudeep/AZ-204-DevelopingSolutionsforMicrosoftAzure-master/Allfiles/Labs/02/Starter/func/func.csproj]
/home/sudeep/.nuget/packages/microsoft.net.sdk.functions/1.0.36/build/Microsoft.NET.Sdk.Functions.Build.targets(44,5): error : You can resolve the problem by installing the specified framework and/or SDK. [/home/sudeep/AZ-204-DevelopingSolutionsforMicrosoftAzure-master/Allfiles/Labs/02/Starter/func/func.csproj]
/home/sudeep/.nuget/packages/microsoft.net.sdk.functions/1.0.36/build/Microsoft.NET.Sdk.Functions.Build.targets(44,5): error :  [/home/sudeep/AZ-204-DevelopingSolutionsforMicrosoftAzure-master/Allfiles/Labs/02/Starter/func/func.csproj]
/home/sudeep/.nuget/packages/microsoft.net.sdk.functions/1.0.36/build/Microsoft.NET.Sdk.Functions.Build.targets(44,5): error : The specified framework can be found at: [/home/sudeep/AZ-204-DevelopingSolutionsforMicrosoftAzure-master/Allfiles/Labs/02/Starter/func/func.csproj]
/home/sudeep/.nuget/packages/microsoft.net.sdk.functions/1.0.36/build/Microsoft.NET.Sdk.Functions.Build.targets(44,5): error :   - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=cbld.10-x64 [/home/sudeep/AZ-204-DevelopingSolutionsforMicrosoftAzure-master/Allfiles/Labs/02/Starter/func/func.csproj]
/home/sudeep/.nuget/packages/microsoft.net.sdk.functions/1.0.36/build/Microsoft.NET.Sdk.Functions.Build.targets(44,5): error :  [/home/sudeep/AZ-204-DevelopingSolutionsforMicrosoftAzure-master/Allfiles/Labs/02/Starter/func/func.csproj]
/home/sudeep/.nuget/packages/microsoft.net.sdk.functions/1.0.36/build/Microsoft.NET.Sdk.Functions.Build.targets(44,5): error : Metadata generation failed. [/home/sudeep/AZ-204-DevelopingSolutionsforMicrosoftAzure-master/Allfiles/Labs/02/Starter/func/func.csproj]
    2 Warning(s)
    2 Error(s)

Time Elapsed 00:00:01.16`

**Comment by sudlo** [comment] 2021-12-19 15:19
can some one help

**Comment by kaushikganguli** [comment] 2021-12-19 17:30
## Following this thread..

**Comment by sudlo** [comment] 2021-12-25 05:35
Hi , '

can any one help us out

**Comment by MOC-Labs-Review** [comment] 2022-02-01 15:31
MOC-Labs-Review found Lab 02 Exercise 2 worked as written

**Comment by JeffKoMS** [comment] 2022-02-01 19:51
@sudlo @kaushikganguli Can you let us know which hosting provider you are using where you're seeing this error?

**Comment by sudlo** [comment] 2022-02-01 20:02
@JeffKoMS  i am using cloud shell..

**Comment by EricCote** [comment] 2022-02-08 06:17
Short answer: The cloud shell is not compatible to run the lab.  

Long answer: Seems that your cloud shell is using an older version of .NET core: v2.1

You can run the following command to validate the installed version:

dotnet --list-sdks
dotnet --list-runtimes

When I checked my own cloud shell, it is using an older version of the .NET sdk: 3.1.403.  (my guess: my shell was created at a later date than yours.)

You could get a more recent 3.1 or even .net 6 version. 

There is some talk over here about how to install a new sdk on the cloud shell over here: https://docs.microsoft.com/en-us/answers/questions/203560/cloud-shell-it-was-not-possible-to-find-any-compat.html

**Comment by MOC-Labs-Review** [comment] 2022-04-11 20:37
MOC Labs Review did not experience this issue.

**Comment by JeffKoMS** [comment] 2022-04-14 18:21
Closing issue since it appears issue was caused by an outdated cloud shell.

**Closed by JeffKoMS** 2022-04-14 18:21 UTC
