### ISSUE TITLE
Incorrect JSON response from API Management xml-to-json outbound processing

### ISSUE THREAD

**Issue by jkataja** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#73] opened 2020-07-01 13:20 UTC
# Module: Lab: Creating a multi-tier solution by using services in Azure
#### Step: 11. Replace that block of XML with the following XML:

The **xml-to-json** outbound processing step in API Management returns invalid JSON. JSON does not allow for comments, but the returned data contains C-style comments. It should work fine in JavaScript but not with JSON parser.

Repro steps:

1. on step 11, add *xml-to-json* outbound processing step
1. on step 16, _Observe the results of the API request_, the response contains comments.

Page to the task:
https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/blob/master/Instructions/Labs/AZ-204_08_lab_ak.md#task-3-manipulate-an-api-response

**Comment by jkataja** [comment] 2020-07-01 13:26
<img width="323" alt="Annotation 2020-07-01 152548" src="https://user-images.githubusercontent.com/1532912/86249178-34ef7280-bbaf-11ea-9c1e-d043ee8e3ada.png">

**Comment by seesharprun** [comment] 2020-08-17 14:27
Closed by design. The lab only shows the student how to convert from XML to JSON, but you never do anything with the JSON data. To add a step to cleanse the JSON would increase the length of the lab beyond acceptable parameters.

**Closed by seesharprun** 2020-08-17 14:27 UTC
