### ISSUE TITLE
Lab 10 Ex 3 Task 2: Student instructions formatting issue

### ISSUE THREAD

**Issue by adntobias** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#391] opened 2022-02-10 12:55 UTC
# Module: 10
##### Step: 11

Description of issue

In the Instruction that should be provided to the students is an odd formating at the beginning of the code snippet.
The start of the try-catch-block is out of the scope.

https://microsoftlearning.github.io/AZ-204-DevelopingSolutionsforMicrosoftAzure/Instructions/Labs/AZ-204_lab_10.html#exercise-3-create-a-net-core-project-to-read-messages-from-a-service-bus-queue

in the .md files it seems like the correct formatting.
https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure/blob/master/Instructions/Labs/AZ-204_lab_10.md#task-2-read-messages-from-an-azure-service-bus-queue

Repro steps:

1.
1.
1
![2022-02-10_13h43_47](https://user-images.githubusercontent.com/55876240/153410924-51608e64-78bb-4b63-9595-9bd9affa3588.png)
.

**Comment by VitalyMCT** [comment] 2022-02-10 12:58
Duplicate of #356

**Comment by JeffKoMS** [comment] 2022-02-11 17:45
This issue is fixed - was missing closing back ticks for the code block and also the CRLF at the end of the opening back ticks wasn't registering.

**Closed by JeffKoMS** 2022-02-11 17:45 UTC
