### ISSUE TITLE
lab 06 NU1100: Unable to resolve 'Microsoft.Identity.Client (>= 4.7.1)' for 'net5.0'

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure#286] opened 2021-09-08 07:25 UTC
# Module: 06
#### Step: 06

Description of issue
Exercise 2: Obtain a token by using the MSAL.NET library
Task 1: Create a .NET project
6. At the command prompt, enter the following command, and then select Enter to import version 4.7.1 of Microsoft.Identity.Client from NuGet:

**dotnet add package Microsoft.Identity.Client --version 4.7.1**

When I run this in the Terminal of Visual Studio Code, I get several errors.

I have installed the following on my Windows 10 Build 1904
1. **Node.js windows installer** https://nodejs.org/dist/v14.17.6/node-v14.17.6-x64.msi
2. **Core Tools installer,** func-cli-x64.msi from [https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=windows%2Ccsharp%2Cportal%2Cbash%2Ckeda]
![image](https://user-images.githubusercontent.com/24426530/132464339-7294df21-d037-4eef-84d0-00e02dce1a91.png)

Repro steps:

1.
1.
1.

**Comment by WigF1** [comment] 2021-09-12 20:29
@dpapkin The labs target .NET Core 3.1 by design. You are trying to target .NET 5.0 and as such may need to work out what the dependency versions are yourself. I'm not sure the lab authors will regard this as an issue, although I cannot speak for them.

**Comment by dpapkin** [comment] 2021-09-13 08:20
Hi Steve,

WHat do I need to install to run this locally?

I installed the follwoing

5) Download and install azure-functions-core-tools v3

a) Download the Node.js  Windows Installer (.msi)<https://nodejs.org/dist/v14.17.6/node-v14.17.6-x64.msi>


Appreciate your help

David
________________________________

**Comment by JeffKoMS** [comment] 2021-10-15 22:31
We just pushed updated instructions for all of the labs. Please reopen if the issue wasn't resolved in that update.

**Closed by JeffKoMS** 2021-10-15 22:31 UTC
